package dev.tilesmile.supernote;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;

/** Authoritative 8-bit tones. Dots never enter this model. Confined to its owner thread. */
final class ToneDocument {
    static final int MAX_PIXELS = 1920 * 2560;
    private static final int TILE = 64;
    private static final int HISTORY_BYTES = 32 * 1024 * 1024;
    final int width, height;
    private final byte[] tones;
    private final boolean[] captured;
    private final LinkedHashMap<Integer, byte[]> before = new LinkedHashMap<>();
    private final ArrayDeque<Edit> undo = new ArrayDeque<>(), redo = new ArrayDeque<>();
    private int historyBytes;
    private boolean editing;
    private int left, top, right, bottom;

    ToneDocument(int width, int height) {
        this(width, height, paper(width, height));
    }
    ToneDocument(int width, int height, byte[] source) {
        validateSize(width, height);
        if (source.length != width * height) throw new IllegalArgumentException("Wrong tone count");
        this.width = width; this.height = height; tones = source.clone();
        captured = new boolean[columns() * ((height + TILE - 1) / TILE)];
        clearDirty();
    }
    static void validateSize(int width, int height) {
        if (width <= 0 || height <= 0 || width > 4096 || height > 4096
                || (long)width * height > MAX_PIXELS) throw new IllegalArgumentException("Invalid canvas size");
    }
    private static byte[] paper(int width, int height) {
        validateSize(width, height);
        byte[] bytes = new byte[width * height]; Arrays.fill(bytes, (byte)255); return bytes;
    }
    int tone(int x, int y) { return tones[y * width + x] & 255; }
    int strokeBaseTone(int x, int y) {
        int key=(y/TILE)*columns()+x/TILE;
        if(!captured[key]) return tone(x,y);
        int tileWidth=Math.min(TILE,width-(x/TILE)*TILE);
        return before.get(key)[(y%TILE)*tileWidth+x%TILE]&255;
    }
    byte[] snapshot() { return tones.clone(); }
    void begin() {
        if (editing) throw new IllegalStateException("Finish the current gesture first");
        editing = true; before.clear();
    }
    void setTone(int x, int y, int gray) {
        if (!editing) throw new IllegalStateException("No active gesture");
        if (gray < 0 || gray > 255) throw new IllegalArgumentException("Invalid tone");
        if (x < 0 || y < 0 || x >= width || y >= height) return;
        if (tone(x, y) == gray) return;
        int key = (y / TILE) * columns() + x / TILE;
        if (!captured[key]) { before.put(key, copyTile(key)); captured[key] = true; }
        tones[y * width + x] = (byte)gray;
        left = Math.min(left, x); top = Math.min(top, y);
        right = Math.max(right, x + 1); bottom = Math.max(bottom, y + 1);
    }
    /** Apply opaque logical raster pixels, generated by the accepted Android circle rasterizer. */
    void paintMask(int[] mask, int stride, int x, int y, int w, int h, int gray) {
        for (int row = 0; row < h; row++) for (int col = 0; col < w; col++) {
            if ((mask[row * stride + col] >>> 24) != 0) setTone(x + col, y + row, gray);
        }
    }
    boolean finish() {
        if (!editing) return false;
        editing = false;
        ArrayList<TileEdit> tiles = new ArrayList<>();
        for (Map.Entry<Integer, byte[]> entry : before.entrySet()) {
            captured[entry.getKey()] = false;
            byte[] after = copyTile(entry.getKey());
            if (!Arrays.equals(entry.getValue(), after))
                tiles.add(new TileEdit(entry.getKey(), entry.getValue(), after));
        }
        before.clear();
        if (tiles.isEmpty()) return false;
        for (Edit edit : redo) historyBytes -= edit.bytes;
        redo.clear();
        Edit edit = new Edit(tiles); undo.addLast(edit); historyBytes += edit.bytes;
        while (historyBytes > HISTORY_BYTES && undo.size() > 1) historyBytes -= undo.removeFirst().bytes;
        return true;
    }
    boolean canUndo() { return !undo.isEmpty(); }
    void trimHistory(int budget) {
        while(historyBytes>budget&&undo.size()>1)historyBytes-=undo.removeFirst().bytes;
        while(historyBytes>budget&&!redo.isEmpty())historyBytes-=redo.removeFirst().bytes;
    }
    /** Clear all disconnected marks as one undoable edit, retaining canvas dimensions. */
    boolean clear() {
        begin();
        for(int key=0;key<captured.length;key++) {
            byte[] tile=copyTile(key);boolean marked=false;
            for(byte tone:tile) if(tone!=(byte)255){marked=true;break;}
            if(marked){before.put(key,tile);captured[key]=true;}
        }
        if(!before.isEmpty()) {
            Arrays.fill(tones,(byte)255);left=0;top=0;right=width;bottom=height;
        }
        return finish();
    }
    void cancel() {
        if (!editing) return;
        for (Map.Entry<Integer, byte[]> tile : before.entrySet()) {
            restoreTile(tile.getKey(), tile.getValue()); captured[tile.getKey()] = false;
        }
        before.clear(); editing = false;
    }
    boolean canRedo() { return !redo.isEmpty(); }
    boolean undo() { return travel(undo, redo, false); }
    boolean redo() { return travel(redo, undo, true); }
    private boolean travel(ArrayDeque<Edit> source, ArrayDeque<Edit> target, boolean forward) {
        if (editing) throw new IllegalStateException("Finish the current gesture first");
        if (source.isEmpty()) return false;
        Edit edit = source.removeLast();
        for (TileEdit tile : edit.tiles) restoreTile(tile.key, forward ? tile.after : tile.before);
        target.addLast(edit); return true;
    }
    /** Returns [left, top, right, bottom], without clearing it. */
    int[] dirty() { return right > left && bottom > top ? new int[]{left, top, right, bottom} : null; }
    void clearDirty() { left = width; top = height; right = bottom = 0; }
    void render(int[] pixels, int x, int y, int w, int h) {
        for (int row = 0; row < h; row++) for (int col = 0; col < w; col++)
            pixels[row * w + col] = DotPattern.pixel(tone(x + col, y + row), x + col, y + row);
    }
    private int columns() { return (width + TILE - 1) / TILE; }
    private byte[] copyTile(int key) {
        int x = key % columns() * TILE, y = key / columns() * TILE;
        int w = Math.min(TILE, width - x), h = Math.min(TILE, height - y);
        byte[] copy = new byte[w * h];
        for (int row = 0; row < h; row++) System.arraycopy(tones, (y + row) * width + x, copy, row * w, w);
        return copy;
    }
    private void restoreTile(int key, byte[] data) {
        int x = key % columns() * TILE, y = key / columns() * TILE;
        int w = Math.min(TILE, width - x), h = Math.min(TILE, height - y);
        for (int row = 0; row < h; row++) System.arraycopy(data, row * w, tones, (y + row) * width + x, w);
        left = Math.min(left, x); top = Math.min(top, y);
        right = Math.max(right, x + w); bottom = Math.max(bottom, y + h);
    }
    private static final class TileEdit {
        final int key; final byte[] before, after;
        TileEdit(int key, byte[] before, byte[] after) { this.key = key; this.before = before; this.after = after; }
    }
    private static final class Edit {
        final ArrayList<TileEdit> tiles; final int bytes;
        Edit(ArrayList<TileEdit> tiles) {
            this.tiles = tiles; int count = 0;
            for (TileEdit tile : tiles) count += tile.before.length + tile.after.length;
            bytes = count;
        }
    }
}
