cmake_minimum_required(VERSION 3.22.1)
project(monopaint_display C)
add_library(monopaint_display SHARED direct_eink.c viewport_bitmap.c)
set_source_files_properties(viewport_bitmap.c PROPERTIES COMPILE_OPTIONS "-O2")
target_compile_options(monopaint_display PRIVATE -Wall -Wextra -Werror)
target_link_libraries(monopaint_display jnigraphics)
